service: cloudwatch-logs

plugins:
 - serverless-pseudo-parameters
 - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  
functions:
  ship-logs-to-logzio:
    handler: functions/ship-logs/handler.handler
    description: Sends CloudWatch logs to Logz.io
    environment:
      logstash_host: <INSERT VALUE HERE>
      logstash_port: <INSERT VALUE HERE>
      token: <INSERT VALUE HERE>

  set-retention:
    handler: functions/set-retention/handler.handler
    description: Sets the log retention policy to the specified no. of days
    environment:
      retention_days: 7
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "logs:PutRetentionPolicy"
        Resource: "*"
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.logs
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - logs.amazonaws.com
              eventName:
                - CreateLogGroup

  subscribe:
    handler: functions/subscribe/handler.handler
    description: Subscribe logs to the ship-logs-to-logzio function
    environment:
      dest_func: "${self:service}-${self:provider.stage}-ship-logs-to-logzio"
      account_id: "#{AWS::AccountId}"
      prefix: "/"
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "logs:PutSubscriptionFilter"
        Resource: "*"
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.logs
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - logs.amazonaws.com
              eventName:
                - CreateLogGroup

resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::Join:
            - ""
            - - "Ref" : "ShipDashlogsDashtoDashlogzioLambdaFunction"
        Principal: logs.#{AWS::Region}.amazonaws.com